### ISSUE TITLE
[Bug] JEI compatibility with Apotheosis (5.8.0) doesn't work (1.18.2) (ForgeML)

### ISSUE THREAD

**Issue by Stryckoeurz** [shedaniel/REIPluginCompatibilities-Issues#46] opened 2023-06-29 11:49 UTC
### What happened?

FML sends the typical mod error when loading.
"JEI" is 9.999 instead of "JEI" ten expected by Apotheosis so it breaks the JEI compat' 
(REI 8.3.618 and REIPC 8.0.46)

### Relevant log output

```shell
-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraftforge.logging.CrashReportExtender.lambda$dumpModLoadingCrashReport$7(CrashReportExtender.java:58) ~[forge-1.18.2-40.2.9-universal.jar%23121!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
-- MOD apotheosis --
Details:
	Mod File: /D:/Overwolf/Instances/AHS (pronounced ass) All Hail Sequencia/mods/Apotheosis-1.18.2-5.8.0.jar
	Failure message: Mod apotheosis only supports jei 10 or above
		Currently, jei is 9.9999
	Mod Version: 5.8.0
	Mod Issue URL: NOT PROVIDED
	Exception message: MISSING EXCEPTION MESSAGE
```

### Anything else?

Apotheosis 5.8.0 does that, previous version (5.7.7 and <5.7.7) don't do that, it's a change on their side and they include at the bottom of their lastest 1.18 changelog they changed it to JEI 10

Relevant Apotheosis changelog concerning JEI 10 being used : https://github.com/Shadows-of-Fire/Apotheosis/blob/1.18/changelog.md

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by shedaniel** [comment] 2023-06-29 11:50
Duplicate of #44

**Closed as completed by shedaniel** 2023-06-29 11:50 UTC
Labels: bug
