### ISSUE TITLE
[Bug] 1.18.2 Forge - Compass not being pulled in crafting

### ISSUE THREAD

**Issue by Raidobw2** [shedaniel/REIPluginCompatibilities-Issues#11] opened 2022-06-30 04:04 UTC
### What happened?

Hello, when crafting recipes using the "+" in REI, all recipes do not pull the compass into the grid for you automatically. The clock also has the same behavior as well.

Versions:
Minecraft `1.18.2`
Forge `40.1.52`
REI `RoughlyEnoughItems-8.3.501.jar`
REI Hacks `RoughlyEnoughItems-jei-internals-workaround-8.3.501.jar`
Modpack `FTB Plexiglass Mountain 1.1.1`

Steps to reproduce:
1. Grab the ingredients to make a map (8 paper and 1 compass)
2. Open the gui of a crafting table
3. Press 'u' on a compass for recipes using it
4. Find the map recipe and click the "+" next to it

![image](https://user-images.githubusercontent.com/17010632/176589842-dd0c5a13-f540-434d-be79-54eb1010c285.png)

https://user-images.githubusercontent.com/17010632/176589858-bdf01014-f293-4357-a0e2-61ffeb8159c3.mp4

### What mod loaders are you seeing the problem on?

Forge

### What do you think this bug is of?

- [ ] Visual
- [X] Recipe Lookup
- [ ] Cheat Mode
- [ ] Plugin Integration / JEI Plugin Compatibility
- [ ] Others

### Relevant log output

```shell
There is nothing in the logs anywhere about this sorry
```

### Anything else?

Thank you in advance for investigating!

**Comment by shedaniel** [comment] 2022-11-17 16:14
Closing this as this is caused by Quark.

**Closed by shedaniel** 2022-11-17 16:14 UTC
Labels: bug
