### ISSUE TITLE
[1.18.2][Bug] Incompatible With Polymorph

### ISSUE THREAD

**Issue by MCBEModder2020** [shedaniel/REIPluginCompatibilities-Issues#47] opened 2023-07-01 00:20 UTC
### What happened?

[ne.mi.fm.lo.ModSorter/LOADING]: Unsupported installed optional dependencies:
	Mod ID: 'jei', Requested by: 'polymorph', Expected range: '[10,)', Actual version: '9.9999'

### Relevant log output

```shell
[ne.mi.fm.lo.ModSorter/LOADING]: Unsupported installed optional dependencies:
	Mod ID: 'jei', Requested by: 'polymorph', Expected range: '[10,)', Actual version: '9.9999'
```

### Anything else?

[ne.mi.fm.lo.ModSorter/LOADING]: Unsupported installed optional dependencies:
	Mod ID: 'jei', Requested by: 'polymorph', Expected range: '[10,)', Actual version: '9.9999'

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by shedaniel** [comment] 2023-07-01 08:18
Duplicate of #44

**Closed as not planned by shedaniel** 2023-07-01 08:18 UTC
Labels: bug, duplicate
